
export LOG_FILE_NAME=/Users/swiftylions/Documents/SLStoreLogAndOtherFiles/app-deployment.log
export LOG_LEVEL=INFO
export FRONTEND_URL=http://localhost:5173
export DATABASE_HOST=localhost
export DATABASE_PORT=3306
export DATABASE_NAME=slstore
export DATABASE_USERNAME=root
export DATABASE_PASSWORD=root
export JPA_SHOW_URL=false
export HIBERNATE_FORMAT_SQL=false
export STRIPE_API_KEY=sk_test_51SsWlVDrNJEHhbLp80a00t7U2xuEOJRlRFh0jrbiFxS5cpbdrQt4oicoiSB2Q5gA2Pj6MgAL1kTpGkExwUjboeLL00nIa5T2pi
export CONTACT_PHONE=+989380546332
export CONTACT_EMAIL=hussein_khanjani@hotmail.com
export CONTACT_ADDRESS=Iran Karaj Fardis Esteghlal Square